from __future__ import print_function

print('in user.py', flush=True)
raise Exception('this is an exception')
